image:
  name: sonarsource/sonar-scanner-cli:latest
  entrypoint: [""]
variables:
  SONAR_TOKEN: "f87bb141dc6c181e8c73f2fd3c02f1c236d22388"
  SONAR_HOST_URL: "http://192.46.213.24:7000/"
  GIT_DEPTH: 0
sonarqube-check:
  stage: test
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - master
    - stable-version
    - Merge_Branches
