image:
  name: sonarsource/sonar-scanner-cli:latest
  entrypoint: [""]
variables:
  SONAR_TOKEN: "0c7950df40258434c7d56fe4683c0b053ae4b850"
  SONAR_HOST_URL: "http://192.168.1.173:7000"
  GIT_DEPTH: 0
sonarqube-check:
  stage: test
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - master
    - stable-version
    - Merge_Branches
