import { environment } from './../../environments/environment';
const domain = environment.apiDomain + '/api/';
const company = JSON.parse(localStorage.getItem('company'))

export const GitToken = {
  token: `VhuWqcBf5HZXLXnX2KV3`,
  uiToken: `glpat-X3RjBzJotUq-qSHiJUf9`
}

export const Doctypes = {
  invoices: `Invoices`,
  excelUploadInvoices: `Excel upload Stats`,
  company: `company`,
  creditNotes: `Credit Note Items`,
  cancelledInvoices: `Cancelled Invoices Details`,
  gspApis: `GSP APIS`,
  sacCodes: `SAC HSN CODES`,
  paymentTypes: `Payment Types`,
  taxPayers: `TaxPayerDetail`,
  user: `User`,
  role: `Role`,
  report: `Report`,
  file: `File`,
  emailTemplates: `Email Template`,
  deleteDocument: `Deleted Document`,
  emailLogs: `Email Queue`,
  benchSettings: `Bench Settings`,
  benchMangerCmd: `Bench Manager Command`,
  updateLogs: `Update Logs`,
  socNotifications: `Socket Notification`,
  documentBin: `Document Bin`,
  emailQueue: `Email Queue`,
  emailDomain: `Email Domain`,
  emailAccount: `Email Account`,
  invoiceReconciliation: `Invoice Reconciliations`,
  irnObj: `IRN Objects`,
  errLogs: `Error Log`,
  posChecks: `POS Checks`,
  posPrinters: `POS Printers`,
  outlets: `Outlets`,
  posPrintSettings: `POS Print Settings`,
  tablet: `Active Tablets`,
  workStations: `Active Work Stations`,
  tabletConfig: `Tablet Config`,
  paymentRecon: `Invoice Payments`,
  information_invoice: `Information Invoices`,
  summaries: `Summaries`,
  events: `Events`,
  summaryPayments: `Summary Payments`,
  contacts: `Contacts`,
  TaxPayerDetail: `TaxPayerDetail`,
  TaxPayerDetails: `Taxpayer Details`,
  TaxPayerLocation: `Taxpayer Locations`,
  summaryDocuments: `Summary Documents`,
  documentTypes: `Document Types`,
  summaryContacts: `Summary Contacts`,
  items: `Items`,
  dispatchInfo: `Dispatch Details`,
  companyUserMap: `Company User Mapping`,
  userMap: `User Mapping`,
  gsps: `GSP API Details`,
  gstr2a: `GSTR 2A`,
  roles: `Role`,
  groups: `Company Groups`,
  gstrSavedData: `Gstr One Saved Details`,
  property: `Properties`,
  bankDetails: `Bank Details`,
  clbsSettings: `CLBS Settings`,
  summaryEmailTracking: `Summary Email Tracking`,
  reconDetails: `Recon Details`,
  userSignature: `User Signature`,
  syncLogs: `Sync Logs`,
  EzygstSettings: `EzyGST Settings`,
  syncConf: `Sync Configrations`

}

export const ApiUrls = {
  resource: domain + `resource`,
  getClient: domain + `method/frappe.client.get_value`,
  getCompanyList: domain + `method/frappe.desk.search.search_link`,
  login: domain + 'method/login',
  company: domain + `resource/${Doctypes.company}`,
  creditNoteSummary: domain + `resource/${Doctypes.creditNotes}`,
  invoices: domain + `resource/${Doctypes.invoices}`,
  posChecks: domain + `resource/${Doctypes.posChecks}`,
  information_invoice: domain + `resource/${Doctypes.information_invoice}`,
  excelUploadInvoices: domain + `resource/${Doctypes.excelUploadInvoices}`,
  cancelledInvoiceDetails: domain + `resource/${Doctypes.cancelledInvoices}`,
  uploadFile: domain + `method/upload_file`,
  gspApis: domain + `resource/${Doctypes.gspApis}`,
  generateIrn: domain + `method/runserverobj`, // (403 err, replaced)
  // generateIrn: domain + `method/version2_app.version2_app.doctype.invoices.invoices.cancelIrn`,
  generateIrn_new: domain + `method/version2_app.version2_app.doctype.invoices.invoices.generateIrn`,
  permanentInvoice: domain + `method/frappe.client.submit`,
  frappeCancelIrn: domain + `method/frappe.desk.form.save.cancel`,
  amendDoc: domain + `method/frappe.client.is_document_amended`,
  taxPayers: domain + `method/version2_app.version2_app.doctype.tax_payer_details.tax_payer_details.getTaxPayerDetails`,
  taxPayersDetails: domain + `method/version2_app.version2_app.doctype.tax_payer_details.tax_payer_details.TaxPayerDetails`,
  dashboard: domain + `method/frappe.desk.doctype.dashboard_chart.dashboard_chart.get`,
  sacHsn: domain + `resource/${Doctypes.sacCodes}`,
  paymentTypes: domain + `resource/${Doctypes.paymentTypes}`,
  taxPayerDefault: domain + `resource/${Doctypes.taxPayers}`,
  reinitiate: domain + `method/version2_app.parsers.`,
  new_reinitiate: domain + `method/version2_app.parsers_invoice.invoice_parsers.`,
  // reinitiate: domain + `method/version2_app.version2_app.doctype.invoices.reinitiate_parser.reinitiateInvoice`,
  permissions: domain + `method/frappe.desk.form.load.getdoc`,
  perDoctype: domain + `method/frappe.desk.form.load.getdoctype`,
  userRoles: domain + `method/version2_app.version2_app.doctype.company.company.getUserRoles`,
  users: domain + `resource/${Doctypes.user}`,
  roles: domain + `resource/${Doctypes.role}`,
  errorLog: domain + `resource/${Doctypes.errLogs}`,
  rolePermissions: domain + `method/frappe.core.doctype.user.user.get_perm_info`,
  roleByUser: domain + `method/frappe.desk.reportview.get`,
  sacSummaries: domain + `method/version2_app.version2_app.doctype.getHsn_sac_code.getTotalamount`,
  creditSummaries: domain + `method/version2_app.version2_app.doctype.getCreditnote.getCreditnote`,
  reports: domain + `method/frappe.desk.query_report.run`,
  exportReports: domain + `method/frappe.core.doctype.access_log.access_log.make_access_log`,
  reportMethod: domain + `method/version2_app.version2_app.doctype.company.reportsDownload.Report_Download`,
  reportList: domain + `resource/${Doctypes.report}`,
  deleteReportFile: domain + `method/version2_app.version2_app.doctype.company.reportsDownload.Report_Delete`,
  getEmailTemplates: domain + `method/frappe.desk.search.search_link`,
  getEmailTempData: domain + `method/frappe.email.doctype.email_template.email_template.get_email_template`,
  sendEmail: domain + `method/frappe.core.doctype.communication.email.make`,
  filesPath: domain + `resource/${Doctypes.file}`,
  fileSave: domain + `method/frappe.desk.form.save.savedocs`,
  changePassword: domain + `method/frappe.core.doctype.user.user.reset_password?user=`,
  networkStatus: domain + `method/version2_app.version2_app.doctype.company.checkInternet.CheckInternetConnection`,
  emailTemplates: domain + `method/version2_app.version2_app.doctype.emailTemplat.emailTemplate`,
  getPrinters: domain + `method/version2_app.version2_app.doctype.company.company.getPrinters`,
  print: domain + `method/version2_app.version2_app.doctype.company.company.givePrint`,
  benchUpdate: domain + `method/version2_app.version2_app.doctype.company.company.console_command`,
  benchUpdate_new: domain + `method/version2_app.version2_app.doctype.company.company.gitpull`,
  customEmailTemplates: domain + `method/frappe.printing.doctype.print_settings.print_settings.is_print_server_enabled`,
  addUserRoles: domain + `method/version2_app.version2_app.doctype.getUserRoles.getUserRoles`,
  reAttach: domain + `method/version2_app.version2_app.doctype.invoices.attach_qr_code.AttachQrCodeInInvoice`,
  generateQR: domain + `method/version2_app.version2_app.doctype.invoices.invoices.send_invoicedata_to_gcb`,
  checkUpdates: domain + `method/version2_app.version2_app.doctype.company.company.gitCurrentBranchCommit`,
  tempLineItemEdit: domain + `method/version2_app.version2_app.doctype.invoices.reinitate_invoice.reprocess_calulate_items`,
  manualCreditNotes: domain + `method/version2_app.verssion2_app.doctype.invoices.credit_manual_invoice.CreditManualInvoice`,
  creditInvoice: domain + `resource/Invoices`,
  cal_items: domain + `method/version2_app.version2_app.doctype.invoices.invoices.calulate_items`,
  sac_items: domain + `method/version2_app.version2_app.doctype.invoices.reinitate_invoice.Reinitiate_invoice`,
  redo_err_invoices: domain + `method/version2_app.version2_app.doctype.company.company.reprocess_error_inoices`,
  file_parser: domain + `method/version2_app.version2_app.doctype.invoices.invoice_parser.file_parsing`,
  emailSend: domain + `method/version2_app.version2_app.doctype.company.company.make`,
  gspToken: domain + `method/version2_app.version2_app.doctype.invoices.invoices.updatelogin_gsp`,
  covertToCredit: domain + `method/version2_app.version2_app.doctype.invoices.manual_tax_invoice.Convert_to_manual_tax_invoice`,
  restoreFile: domain + `method/frappe.core.doctype.deleted_document.deleted_document.restore`,
  xlBulkInvoice: domain + `method/version2_app.version2_app.doctype.invoices.manual_upload.manual_upload`,
  sendEmailQueue: domain + `method/frappe.email.doctype.email_queue.email_queue.send_now`,
  deleteInvoices: domain + `method/frappe.desk.reportview.delete_items`,
  migrateBench: domain + `method/version2_app.version2_app.doctype.company.company.bench_migrate`,
  getErrInvoices: domain + `method/version2_app.version2_app.doctype.company.company.errorInvoicesList`,
  clearNotifications: domain + `method/version2_app.version2_app.doctype.socket_notification.socket_notification.DeleteNotifications`,
  parserFile: domain + `method/version2_app.version2_app.doctype.company.get_parsers_file_path.get_parser_filePath`,
  Uiupdate: domain + `method/version2_app.version2_app.doctype.company.company.updateUiProd`,
  uiUpdateGitCommit: domain + `method/version2_app.version2_app.doctype.company.company.gitUiBranchCommit`,
  updateParsers: domain + `method/version2_app.version2_app.doctype.company.company.update_parsers`,
  checkProxy: domain + `method/version2_app.version2_app.doctype.company.company.updateProxySettings`,
  reprocessBulkUpload: domain + `method/version2_app.version2_app.doctype.invoices.bulk_upload_reprocess.BulkUploadReprocess`,
  reconcilationCount: domain + `method/version2_app.version2_app.doctype.invoice_reconciliations.invoice_reconciliations.invoicereconciliationcount`,
  pendingIrnObj: domain + `method/version2_app.version2_app.doctype.irn_objects.irn_objects.IrnObject`,
  diskSpace: domain + `method/version2_app.version2_app.doctype.company.company.diskspace`,
  totalCount: domain + `method/version2_app.version2_app.doctype.dashboard_apis.invoicecategorycount`,
  invoiceDetailsCount: domain + `method/version2_app.version2_app.doctype.dashboard_apis.invoicedetailscount`,
  gstrStatistics: domain + `method/version2_app.version2_app.doctype.dashboard_apis.GSTR1Statistics`,
  invoiceReconsiliationCount: domain + `method/version2_app.version2_app.doctype.dashboard_apis.invoicereconsiliationcount`,
  reprocessDocmentBin: domain + `method/version2_app.version2_app.doctype.company.company.reprocess_error_documentbin_invoices`,
  bulkUploadHolidayEx: domain + `method/version2_app.version2_app.doctype.invoices.holiday_manual_upload.holidayinManualupload`,
  gspMetering: domain + `method/version2_app.version2_app.doctype.gsp_metering.gsp_metering.gspmeteringdata`,
  autoAdjustment: domain + `method/version2_app.version2_app.doctype.invoices.reinitate_invoice.auto_adjustment`,
  reconcilation: domain + `method/version2_app.version2_app.doctype.xml_parse.extract_xml`,
  convertToCreditNote: domain + `method/version2_app.version2_app.doctype.invoices.reinitate_invoice.b2b_success_to_credit_note`,
  posPrinterSettings: domain + `method/version2_app.pos_bills.doctype.pos_print_settings.pos_print_settings.pos_printer_settings`,
  posPrintBill: domain + `method/version2_app.pos_bills.doctype.pos_checks.pos_checks.print_pos_bill`,
  tabletReset: domain + `method/version2_app.sign_ezy.doctype.active_tablets.active_tablets.resetworkstation_tablet`,
  dowloadGSTR1: domain + `method/version2_app.version2_app.doctype.company.reportsDownload.gstr1_excel_workbook`,
  updateGSTRDetails: domain + `method/version2_app.version2_app.doctype.invoices.invoices.get_taxpayerdetails`,
  get_tax_payer_details: domain + `method/version2_app.version2_app.doctype.invoices.invoices.get_tax_payer_details`,
  diagnostic: domain + `method/version2_app.events.backup_file_perticulerdoctypes`,
  createBreakUp: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.create_summary_breakup`,
  getBreakup: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.get_summary_breakup`,
  download_pdf: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.download_pdf`,
  contacts: domain + `resource/${Doctypes.contacts}`,
  taxpayerdetails: domain + `resource/${Doctypes.TaxPayerDetail}`,
  taxpayerlocation: domain + `resource/${Doctypes.TaxPayerLocation}`,
  pincodeApi: `https://api.postalpincode.in/pincode/`,
  deleteInvoiceFrmSmry: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.delete_invoice_summary_breakup`,
  updateSummary: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.update_summary_breakup`,
  printFromatsClbs: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.summary_print_formats`,
  summaryPdfFiles: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.download_pdf`,
  updateSummaryData: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.update_summary`,
  submitSummary: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.submit_summary`,
  sendEmailSummary: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.send_summary_mail`,
  version: `${domain}resource/Version`,
  summaryActivityLog: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.get_summaries_activity_log`,
  delete_summary: domain + `method/version2_app.clbs.doctype.summaries.summaries.delete_summaries`,
  //gstr Api's
  gstr2Excel: `${domain}method/gstr2_filing.gstr2_filing.doctype.gstr_2a.gstr_2a.gstr2a_excel`,
  gstr2ATheads: `${domain}method/gstr2_filing.gstr2_filing.doctype.gstr_2a.gstr_2a.get_gstr2a_names`,
  gstr2AMapped: `${domain}method/gstr2_filing.gstr2_filing.doctype.gstr_2a.gstr_2a.gstr2a_data_upload`,
  // addUserRoles: domain + `method/ezy_gst.ezy_gst.doctype.getUserRoles.getUserRoles`,
  gstr2Ab2bData: domain + `method/gstr2_filing.gstr2_filing.doctype.gstr_2a.gstr_2a.gstr2a_filter_totalamountsums`,
  getInvoices: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.getInvoices`,
  userMapping: domain + `method/ezy_gst.ezy_gst.doctype.user_mapping.user_mapping.getUsers`,
  userPropertyMapping: domain + `method/ezy_gst.ezy_gst.doctype.user_mapping.user_mapping.create_update_user_mapping`,
  getUserMapping: domain + `method/ezy_gst.ezy_gst.doctype.user_mapping.user_mapping.get_user_mapping_details`,
  retSave: domain + `method/ezy_gst.ezy_gst.doctype.gsp_util_module.gstr_1_b2b_retsave.retsave_b2b`,
  retSubmit: domain + `method/ezy_gst.ezy_gst.doctype.gsp_util_module.gstr_1_b2b_retsave.ret_save_submit_with_otp`,
  reconcile: domain + `method/ezy_gst.ezy_gst.doctype.gsp_util_module.get_gstr_1_invoices.get_gst_saved_invoices`,
  dashboardGSTR1: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.getGSTR1DashboardDetails`,
  sacHsnSummary: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.getHsnSummary`,
  reconcileSummary: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.getGSTR1ReconciliationSummaryCount`,
  summary_activity_log: domain + `method/version2_app.clbs.doctype.summaries.summaries.summary_activity_log`,
  email_tracking: domain + `resource/${Doctypes.summaryEmailTracking}`,
  export_gstr1_invoices: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.export_invoices`,
  nill_rated_supplies: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.nil_rated_supplies`,
  export_workbook: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.export_workbook`,
  clbsSettings: domain + `resource/${Doctypes.clbsSettings}`,
  nill_rated_items: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.nill_rated_items`,
  document_series: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.document_sequence`,
  reconciliation: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.reconciliation`,
  workbook_export: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.export_workbook_recon`,
  create_reconciliation: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.create_reconciliation`,
  export_recon: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.export_recon`,
  delete_recon: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.delete_recon_file`,
  redo_recon: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.Redo_recon`,
  invoice_recon_dashboard: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.dashborad_recon`,
  invoice_recon_last_updated: domain + `method/version2_app.version2_app.doctype.invoices.ezy_gst_dashboard.last_recon_update`,
  exportInvoiceLineItems: domain + `method/version2_app.version2_app.doctype.items.items.invoice_items`,
  getItemsForPosChecks: domain + `method/version2_app.version2_app.doctype.items.items.get_items_for_pos_checks`,
  updateCheckInItems: domain + `method/version2_app.pos_bills.doctype.pos_checks.pos_checks.update_check_in_items`,
  getPosChecksData: domain + `method/version2_app.pos_bills.doctype.pos_checks.pos_checks.get_pos_checks_clbs`,
  summary_amendment: domain + `method/version2_app.clbs.doctype.summary_breakups.summary_breakups.summary_amendment`,
  update_document_sequence: domain + `method/version2_app.clbs.doctype.document_types.document_types.update_document_sequence`,
  user_name_rename_doc: domain + `method/frappe.rename_doc`,
  e_signature: domain + `method/version2_app.e_signature.e_signature.add_esignature_to_invoice`,
  add_signature_on_etax: domain + `method/version2_app.e_signature.e_signature.add_signature_on_etax`,
  get_amendments: domain + `method/invoice_sync.invoice_sync.report.amendment.amendment.get_amendments`,
  getSync: domain + `method/frappe.desk.form.load.getdoc`,
  syncLogs: domain + `resource/${Doctypes.syncLogs}`,
  // syncLogs: domain + `resource/get_sync_logs`,
  syncLogsDashboard: domain + `method/invoice_sync.sync_dashboard_history.get_total_dashboard_count_sync_history`,
  // sync_data_from_web_dashboard: domain + `method/invoice_sync.invoice_sync.doctype.sync_logs.sync_logs.sync_data_from_web`,
  sync_data_from_web: domain + `method/invoice_sync.invoice_sync.doctype.sync_logs.sync_logs.sync_invoices_bulk`,

  sync_data_to_erp_single: domain + `method/invoice_sync.invoice_sync.doctype.sync_logs.sync_logs.sync_data_to_erp_single`,
  sync_data_to_erp: domain + `method/invoice_sync.invoice_sync.doctype.sync_logs.sync_logs.sync_data_to_erp`,
  manual_sync_taxpayer_details: domain + `method/invoice_sync.invoice_sync.doctype.sync_logs.sync_logs.manual_sync_taxpayer_details`,
  manual_sync_items: domain + `method/invoice_sync.invoice_sync.doctype.sync_logs.sync_logs.manual_sync_items`,
  EzygstSettings: domain + `resource/${Doctypes.EzygstSettings}`,
  get_data_amendment_sac_hsn_summary: domain + `method/invoice_sync.invoice_sync.report.amendment_sac_hsn_summary.amendment_sac_hsn_summary.get_data`,
  bulk_sync_ezygst: domain + `method/invoice_sync.invoice_sync.doctype.sync_logs.sync_logs.bulk_sync_ezygst`,
  accept_amendments: domain + `method/invoice_sync.invoice_sync.doctype.sync_logs.sync_logs.accept_amendments`,
  missing_irn_generation: domain + `method/version2_app.version2_app.doctype.invoices.e_invoice_missing_count.get_missing_count`,
  validate_irn_gen_date: domain + `method/version2_app.version2_app.doctype.invoices.e_invoice_missing_count.check_invoice_date_if_graterthan_days`,
  report_for_invoices: domain + `method/version2_app.version2_app.doctype.invoices.e_invoice_missing_count.download_due_and_expired_reports`,
  reprocess_B2C_pending_invoices: domain + `method/version2_app.version2_app.doctype.company.company.reprocess_B2C_pending_invoices`,
  reSync_based_on_from_to_dates: domain + `method/invoice_sync.invoice_sync.doctype.sync_logs.sync_logs.desync_invoices`,
  export_as_excel_errorlogs: domain + `method/invoice_sync.invoice_sync.doctype.sync_logs.sync_logs.export_error_sync_logs`,
  redo_error: domain + `method/version2_app.version2_app.doctype.company.company.reprocess_error_documentbin_invoices?docdate=2023-07-12`,
  sac_code_details: domain + `method/version2_app.version2_app.download_taxpayer_details.get_all_sac_code_details`,
  payment_details: domain + `method/version2_app.version2_app.download_taxpayer_details.get_all_payment_details`,
  tax_payer_details: domain + `method/version2_app.version2_app.download_taxpayer_details.get_all_taxpayer_details`,
  update_signature_on_pdf: domain + `method/version2_app.e_signature.e_signature.after_add_signature_for_existing_invoices`,


}
