export const UOMCode = [
    {id:1,code:'BAG',description:'BAGS'},
    {id:2,code:'BAL',description:'BALE'},
    {id:3,code:'BDL',description:'BUNDLES'},
    {id:4,code:'BKL',description:'BUCKLES'},
    {id:5,code:'BOU',description:'BILLION OF UNITS'},
    {id:6,code:'BOX',description:'BOX'},
    {id:7,code:'BTL',description:'BOTTLES'},
    {id:8,code:'BUN',description:'BUNCHES'},
    {id:9,code:'CAN',description:'CANS'},
    {id:10,code:'CBM',description:'CUBIC METERS'},
    {id:11,code:'CCM',description:'CUBIC CENTIMETERS'},
    {id:12,code:'CMS',description:'CENTIMETERS'},
    {id:13,code:'CTN',description:'CARTONS'},
    {id:14,code:'DOZ',description:'DOZENS'},
    {id:15,code:'DRM',description:'DRUMS'},
    {id:16,code:'GGK',description:'GREAT GROSS'},
    {id:17,code:'GMS',description:'GRAMMES'},
    {id:18,code:'GRS',description:'GROSS'},
    {id:19,code:'GYD',description:'GROSS YARDS'},
    {id:20,code:'KGS',description:'KILOGRAMS'},
    {id:21,code:'KLR',description:'KILOLITRE'},
    {id:22,code:'KME',description:'KILOMETRE'},
    {id:23,code:'MLT',description:'MILILITRE'},
    {id:24,code:'MTR',description:'METERS'},
    {id:25,code:'MTS',description:'METRIC TON'},
    {id:26,code:'NOS',description:'NUMBERS'},
    {id:27,code:'PAC',description:'PACKS'},
    {id:28,code:'PCS',description:'PIECES'},
    {id:29,code:'PRS',description:'PAIRS'},
    {id:30,code:'QTL',description:'QUINTAL'},
    {id:31,code:'ROL',description:'ROLLS'},
    {id:32,code:'SET',description:'SETS'},
    {id:33,code:'SQF',description:'SQUARE FEET'},
    {id:34,code:'SQM',description:'SQUARE METERS'},
    {id:35,code:'SQY',description:'SQUARE YARDS'},
    {id:36,code:'TBS',description:'TABLETS'},
    {id:37,code:'TGM',description:'TEN GROSS'},
    {id:38,code:'THD',description:'THOUSANDS'},
    {id:39,code:'TON',description:'TONNES'},
    {id:40,code:'TUB',description:'TUBES'},
    {id:41,code:'UGS',description:'US GALLONS'},
    {id:42,code:'UNT',description:'UNITS'},
    {id:43,code:'YDS',description:'YARDS'},
    {id:44,code:'OTH',description:'OTHERS'}
]